# Generated by Django 4.2.6 on 2023-11-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_daytime_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytime',
            name='day',
            field=models.CharField(choices=[('a', 'Δευτέρα'), ('b', 'Τρίτη'), ('c', 'Τετάρτη'), ('d', 'Πέμπτη'), ('e', 'Παρασκευή'), ('f', 'Σάββατο'), ('g', 'Κυριακή')], max_length=9),
        ),
    ]
