# Generated by Django 4.2.6 on 2023-11-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_daytime_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceptionalrule',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_available',
        ),
    ]
