# Generated by Django 4.2.6 on 2023-11-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_exceptionalrule_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationperiod',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
