# Generated by Django 4.2.6 on 2023-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservationperiod_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationperiod',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
