# Generated by Django 4.2.6 on 2023-11-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservationperiod_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='reservationperiod',
            name='schoolYear',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.schoolyear'),
        ),
    ]
