# Generated by Django 4.2.6 on 2023-11-19 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_day_is_vacation_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationperiod'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_window',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservationwindow'),
        ),
    ]
