# Generated by Django 4.2.7 on 2023-11-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_reservation_terms_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Εκκρεμής'), ('denied', 'Ακυρωμένη'), ('approved', 'Επιβεβαιωμένη')], default='pending', max_length=8),
        ),
    ]
