# Generated by Django 4.2.7 on 2023-11-30 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_alter_reservation_student_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionalrule',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.daytime'),
        ),
    ]
