# Generated by Django 4.2.7 on 2023-12-03 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_alter_exceptionalrule_timeslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
