# Generated by Django 4.2.6 on 2023-10-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
