# Generated by Django 4.2.6 on 2023-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
