# Generated by Django 4.2.6 on 2023-10-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='privacy_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
