# Generated by Django 4.2.6 on 2023-10-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_schooluser_email_schooluser_privacy_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schools.department'),
        ),
    ]
