# Generated by Django 4.2.6 on 2023-11-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_schoolteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolTeam',
        ),
    ]
